# "Guess the number" mini-project
# input will come from buttons and an input field
# all output for the game will be printed in the console
import simplegui
import random

print "Welcome to *Guess the number* Game"
def range100():
    # Calculates the secret number in range 0 to 100
    global secret_num
    secret_num = random.randrange(0,100)  
   # print "secret_num" + str(secret_num) """used for debugging"""
    
def range1000():
    # Calculates the secret number in range 0 to 1000
    global secret_num
    secret_num = random.randrange(0,1000) 
   # print "secret_num" + str(secret_num) """used for debugging"""

#Event handler for key press   
def enter(t):
    #takes the key press, computes number of remaining guesses
    global num_guess
    global secret_num
    global r
    guess = t
    print "Guess was" +' '+ t   
    num_guess = num_guess - 1
    if (num_guess == 0):
        print "You ran out of guesses. The number was", secret_num
        reset() 
    else:
        print "Number of remaining guesses is", num_guess
        input_guess(guess)
  
def reset():
    # calls the right function depending on the range chosen first
    global r
    if ( r == 100):
        call100()
    else:
        call1000()
        
        
    
def input_guess(guess):
    # compares the user input to the secret number generated by computer and prints appropriate text
    global secret_num
    global counter
    n = int(guess)
    if (n < secret_num):
        print "Higher!"
        print
    elif (n > secret_num):
        print "Lower!"
        print
    else:
        print "Correct!"
        print
        reset()
  
  
def new_game():
    # initiates new game and calls the function with correct range
    global num_guess
    global r
    print
    print "New Game"
    if (r ==100):
         print "Range is from 0 to 100"
         range100()
    else:
         print "Range is from 0 to 1000"
         range1000()
    print "Number of remaining guesses is ", num_guess
    print
    
#Event Handler for calling appropriate functions in the range    
def call100():
    # Initializes the global variables for range 0 to 100
    global r
    global num_guess
    r = 100
    num_guess = 7
    new_game()
        
def call1000():
    # Initializes the global variables for range 0 to 1000
    global r
    global num_guess
    r = 1000
    num_guess = 10
    new_game()
    
#create frame    
f = simplegui.create_frame("Guess the number game",300,300)    

# register event handlers for control elements
f.add_button("Range 0-100", call100, 100)
f.add_button("Range 0-1000", call1000, 100)
f.add_input("Enter", enter, 100)

#frame start
f.start()



